# Kleber Garcia (c) 2012
LEVEL = ../..

SRC_FILES = 	platform/posix/PosixSemaphore.cpp \
		platform/posix/PosixMutex.cpp \
		platform/posix/PosixThreadMutex.cpp \
		platform/posix/PosixShm.cpp \
		platform/posix/PosixProcessEvent.cpp \
		platform/posix/PosixThread.cpp \
	        platform/posix/PosixProcess.cpp \
		DefaultThreadFactory.cpp \
		HotQBase.cpp 

include $(LEVEL)/Makefile.inc

$(TARGET) : $(LIB_NAME)
